import type {
  FeaturedCityBlock,
  MarketplaceHomeData,
  MarketplaceListing,
} from "@/lib/marketplace/types";

const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

function listing(
  item: MarketplaceListing & { id: string },
): MarketplaceListing {
  return item;
}

export const MOCK_DEALS: MarketplaceListing[] = [
  listing({
    id: "mock-deal-brickell",
    kind: "property",
    href: "/imoveis?city=Miami&q=Brickell",
    title: "Luxury apartment in Brickell, Miami",
    location: "Brickell, Miami, FL",
    price: 860000,
    originalPrice: 977000,
    discountPercent: 12,
    currency: "USD",
    image: img("photo-1512917774080-9991f1c4c750"),
    type: "apartment",
    verified: true,
    company: "Atlantic Realty",
    badge: "deal",
    bedrooms: 3,
    bathrooms: 2,
    area: 165,
  }),
  listing({
    id: "mock-deal-sp-house",
    kind: "property",
    href: "/imoveis?city=S%C3%A3o%20Paulo&q=pool",
    title: "House with pool in São Paulo",
    location: "Morumbi, São Paulo",
    price: 1850000,
    currency: "BRL",
    image: img("photo-1600596542815-ffad4c1539a9"),
    type: "house",
    verified: true,
    company: "Urban Homes",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
  }),
  listing({
    id: "mock-deal-jeep",
    kind: "vehicle",
    href: "/veiculos?q=Jeep+Compass",
    title: "Jeep Compass 2021 Limited",
    location: "São Paulo, SP",
    price: 128900,
    currency: "BRL",
    image: img("photo-1519641471654-76ce0107ad1b"),
    type: "suv",
    badge: "new",
    year: 2021,
    mileage: 41000,
    make: "Jeep",
    model: "Compass",
    company: "Auto Prime",
  }),
  listing({
    id: "mock-deal-lisbon",
    kind: "property",
    href: "/imoveis?city=Lisbon&type=commercial",
    title: "Commercial building in Lisbon",
    location: "Avenidas Novas, Lisbon",
    price: 2400000,
    currency: "EUR",
    image: img("photo-1486406146926-c627a92ad1ab"),
    type: "commercial",
    badge: "featured",
    area: 890,
    company: "Iberia Commercial",
    verified: true,
  }),
  listing({
    id: "mock-deal-bmw-moto",
    kind: "vehicle",
    href: "/veiculos?type=motorcycle&q=BMW",
    title: "BMW R 1250 GS Adventure",
    location: "Lisbon, Portugal",
    price: 18900,
    originalPrice: 21000,
    discountPercent: 10,
    currency: "EUR",
    image: img("photo-1558981806-ec527fa84c39"),
    type: "motorcycle",
    badge: "deal",
    year: 2022,
    mileage: 8400,
    make: "BMW",
    model: "R 1250 GS",
    company: "Moto Lisboa",
  }),
  listing({
    id: "mock-deal-dubai",
    kind: "project",
    href: "/projetos?city=Dubai",
    title: "Waterfront residences in Dubai Marina",
    location: "Dubai Marina, UAE",
    price: 1250000,
    currency: "USD",
    image: img("photo-1512453979798-5ea266f8880c"),
    type: "apartment",
    badge: "new",
    bedrooms: 2,
    bathrooms: 2,
    area: 142,
    company: "Gulf Developments",
    verified: true,
  }),
];

export const MOCK_FEATURED_PROPERTIES: MarketplaceListing[] = [
  listing({
    id: "mock-prop-vila-nova",
    kind: "property",
    href: "/imoveis?city=S%C3%A3o%20Paulo&q=Vila+Nova",
    title: "Modern apartment in Vila Nova",
    location: "Vila Nova Conceição, São Paulo",
    price: 1280000,
    currency: "BRL",
    image: img("photo-1502672260266-1c1ef2d93688"),
    type: "apartment",
    badge: "premium",
    bedrooms: 3,
    bathrooms: 2,
    area: 128,
    garage: 2,
    verified: true,
    company: "Reeskova Prime",
  }),
  listing({
    id: "mock-prop-pinheiros",
    kind: "property",
    href: "/imoveis?city=S%C3%A3o%20Paulo&q=Pinheiros",
    title: "House with garden in Pinheiros",
    location: "Pinheiros, São Paulo",
    price: 2450000,
    currency: "BRL",
    image: img("photo-1600585154340-be6161a56a0c"),
    type: "house",
    badge: "new",
    bedrooms: 4,
    bathrooms: 3,
    area: 260,
    garage: 3,
    verified: true,
    company: "Urban Homes",
  }),
  listing({
    id: "mock-prop-itaim",
    kind: "property",
    href: "/imoveis?city=S%C3%A3o%20Paulo&q=Itaim",
    title: "Penthouse in Itaim Bibi",
    location: "Itaim Bibi, São Paulo",
    price: 4900000,
    currency: "BRL",
    image: img("photo-1600607687939-ce8a6c25118c"),
    type: "apartment",
    badge: "premium",
    bedrooms: 4,
    bathrooms: 4,
    area: 310,
    garage: 3,
    verified: true,
    company: "Prime Estates",
  }),
  listing({
    id: "mock-prop-miami",
    kind: "property",
    href: "/imoveis?city=Miami&q=oceanfront",
    title: "Oceanfront apartment in Miami",
    location: "Miami Beach, FL",
    price: 1150000,
    currency: "USD",
    image: img("photo-1613490493576-7fde63acd811"),
    type: "apartment",
    badge: "premium",
    bedrooms: 3,
    bathrooms: 2,
    area: 165,
    garage: 1,
    verified: true,
    company: "Atlantic Realty",
  }),
  listing({
    id: "mock-prop-lisbon-office",
    kind: "property",
    href: "/imoveis?city=Lisbon&type=commercial",
    title: "Commercial office in Lisbon",
    location: "Parque das Nações, Lisbon",
    price: 890000,
    currency: "EUR",
    image: img("photo-1497366216548-37526070297c"),
    type: "commercial",
    badge: "featured",
    bathrooms: 2,
    area: 210,
    verified: true,
    company: "Iberia Commercial",
  }),
];

export const MOCK_POPULAR_VEHICLES: MarketplaceListing[] = [
  listing({
    id: "mock-car-civic",
    kind: "vehicle",
    href: "/veiculos?q=Honda+Civic",
    title: "Honda Civic 2022 EX",
    location: "São Paulo, SP",
    price: 112000,
    currency: "BRL",
    image: img("photo-1619767886558-efdc259cde1a"),
    type: "car",
    year: 2022,
    mileage: 32000,
    make: "Honda",
    model: "Civic",
    company: "Honda Premium",
  }),
  listing({
    id: "mock-car-compass",
    kind: "vehicle",
    href: "/veiculos?q=Jeep+Compass",
    title: "Jeep Compass 2021 Limited",
    location: "Campinas, SP",
    price: 128900,
    currency: "BRL",
    image: img("photo-1533473359331-0135ef1b58bf"),
    type: "suv",
    year: 2021,
    mileage: 41000,
    make: "Jeep",
    model: "Compass",
    company: "Auto Prime",
    badge: "featured",
  }),
  listing({
    id: "mock-car-corolla",
    kind: "vehicle",
    href: "/veiculos?q=Toyota+Corolla",
    title: "Toyota Corolla 2023 XEi",
    location: "Curitiba, PR",
    price: 145000,
    currency: "BRL",
    image: img("photo-1621007947382-bb3c3994e3fb"),
    type: "car",
    year: 2023,
    mileage: 18000,
    make: "Toyota",
    model: "Corolla",
    company: "Toyota Center",
  }),
  listing({
    id: "mock-car-bmw",
    kind: "vehicle",
    href: "/veiculos?q=BMW+320i",
    title: "BMW 320i 2020 Sport",
    location: "Rio de Janeiro, RJ",
    price: 198000,
    currency: "BRL",
    image: img("photo-1555215695-300b0a4f4b32"),
    type: "car",
    year: 2020,
    mileage: 52000,
    make: "BMW",
    model: "320i",
    company: "BMW Rio",
    badge: "premium",
  }),
  listing({
    id: "mock-car-tcross",
    kind: "vehicle",
    href: "/veiculos?q=T-Cross",
    title: "Volkswagen T-Cross 2022 Comfortline",
    location: "Belo Horizonte, MG",
    price: 109900,
    currency: "BRL",
    image: img("photo-1549317661-bd32c8ce0db2"),
    type: "suv",
    year: 2022,
    mileage: 29000,
    make: "Volkswagen",
    model: "T-Cross",
    company: "VW Motors",
  }),
];

export const MOCK_NEW_LISTINGS: MarketplaceListing[] = [
  listing({
    id: "mock-new-studio",
    kind: "property",
    href: "/imoveis?city=S%C3%A3o%20Paulo&q=studio",
    title: "Studio in Vila Olímpia",
    location: "Vila Olímpia, São Paulo",
    price: 420000,
    currency: "BRL",
    image: img("photo-1522708323590-d24dbb6b0267", 800),
    type: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    area: 38,
    company: "Urban Homes",
  }),
  listing({
    id: "mock-new-pulse",
    kind: "vehicle",
    href: "/veiculos?q=Fiat+Pulse",
    title: "Fiat Pulse 2023 Drive",
    location: "São Paulo, SP",
    price: 96000,
    currency: "BRL",
    image: img("photo-1503376780353-7e6692767b70", 800),
    type: "suv",
    year: 2023,
    mileage: 12000,
    make: "Fiat",
    model: "Pulse",
  }),
  listing({
    id: "mock-new-land",
    kind: "property",
    href: "/imoveis?city=Campinas&type=land",
    title: "Land in Campinas",
    location: "Campinas, SP",
    price: 380000,
    currency: "BRL",
    image: img("photo-1500382017468-9049fed747ef", 800),
    type: "land",
    area: 450,
    company: "Campo Invest",
  }),
  listing({
    id: "mock-new-copa",
    kind: "property",
    href: "/imoveis?city=Rio%20de%20Janeiro&q=Copacabana",
    title: "Apartment in Copacabana",
    location: "Copacabana, Rio de Janeiro",
    price: 890000,
    currency: "BRL",
    image: img("photo-1560448204-e02f11c3d0e2", 800),
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 92,
    company: "Rio Prime",
  }),
  listing({
    id: "mock-new-ninja",
    kind: "vehicle",
    href: "/veiculos?type=motorcycle&q=Ninja",
    title: "Kawasaki Ninja 400",
    location: "São Paulo, SP",
    price: 32900,
    currency: "BRL",
    image: img("photo-1568772585407-9361f9bf3a87", 800),
    type: "motorcycle",
    year: 2023,
    mileage: 4100,
    make: "Kawasaki",
    model: "Ninja 400",
  }),
  listing({
    id: "mock-new-warehouse",
    kind: "property",
    href: "/imoveis?city=Guarulhos&type=commercial",
    title: "Warehouse in Guarulhos",
    location: "Guarulhos, SP",
    price: 1150000,
    currency: "BRL",
    image: img("photo-1586528116311-ad8dd3c8310d", 800),
    type: "commercial",
    area: 1200,
    company: "LogiPark",
  }),
  listing({
    id: "mock-new-lisbon-apt",
    kind: "property",
    href: "/imoveis?city=Lisbon&q=Chiado",
    title: "Apartment in Chiado",
    location: "Chiado, Lisbon",
    price: 640000,
    currency: "EUR",
    image: img("photo-1502672260266-1c1ef2d93688", 800),
    type: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    area: 78,
    company: "Lisboa Living",
  }),
];

export const MOCK_FEATURED_CITY: FeaturedCityBlock = {
  city: "São Paulo",
  state: "SP",
  country: "Brazil",
  items: [
    listing({
      id: "mock-city-madalena",
      kind: "property",
      href: "/imoveis?city=S%C3%A3o%20Paulo&q=Madalena",
      title: "Apartment in Vila Madalena",
      location: "Vila Madalena, São Paulo",
      price: 980000,
      currency: "BRL",
      image: img("photo-1522708323590-d24dbb6b0267", 800),
      type: "apartment",
      bedrooms: 2,
      bathrooms: 2,
      area: 86,
      company: "Reeskova Prime",
    }),
    listing({
      id: "mock-city-civic",
      kind: "vehicle",
      href: "/veiculos?city=S%C3%A3o%20Paulo&q=Civic",
      title: "Honda Civic 2022",
      location: "São Paulo, SP",
      price: 112000,
      currency: "BRL",
      image: img("photo-1619767886558-efdc259cde1a", 800),
      type: "car",
      year: 2022,
      mileage: 32000,
      make: "Honda",
      model: "Civic",
    }),
    listing({
      id: "mock-city-morumbi",
      kind: "property",
      href: "/imoveis?city=S%C3%A3o%20Paulo&q=Morumbi",
      title: "House in Morumbi",
      location: "Morumbi, São Paulo",
      price: 3200000,
      currency: "BRL",
      image: img("photo-1600596542815-ffad4c1539a9", 800),
      type: "house",
      bedrooms: 5,
      bathrooms: 4,
      area: 420,
      company: "Urban Homes",
    }),
    listing({
      id: "mock-city-office",
      kind: "property",
      href: "/imoveis?city=S%C3%A3o%20Paulo&type=commercial",
      title: "Commercial office",
      location: "Faria Lima, São Paulo",
      price: 1450000,
      currency: "BRL",
      image: img("photo-1497366216548-37526070297c", 800),
      type: "commercial",
      area: 180,
      company: "Iberia Commercial",
    }),
  ],
};

export function getMockMarketplaceHomeData(): MarketplaceHomeData {
  return {
    deals: MOCK_DEALS,
    featuredProperties: MOCK_FEATURED_PROPERTIES,
    newListings: MOCK_NEW_LISTINGS,
    popularVehicles: MOCK_POPULAR_VEHICLES,
    featuredCity: MOCK_FEATURED_CITY,
  };
}
