import type { ServiceListing } from "./types";

export const serviceListings: ServiceListing[] = [
  {
    id: "s1",
    category: "services",
    title: "Home Inspection",
    type: "inspection",
    pricing: "from",
    price: 450,
    currency: "BRL",
    country: "Brasil",
    state: "SP",
    city: "São Paulo",
    description: "Full technical inspection before you buy or rent.",
    provider: "Inspecta Brasil",
    rating: 4.9,
    reviews: 214,
    verified: true,
    topRated: true,
    availableToday: true,
    availableWeek: true,
    image:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80",
    lat: -23.5505,
    lng: -46.6333,
    publishedAt: "2026-08-20",
  },
  {
    id: "s2",
    category: "services",
    title: "Interior Design",
    type: "interior",
    pricing: "from",
    price: 1200,
    currency: "USD",
    country: "United States",
    state: "FL",
    city: "Miami",
    description: "Design packages for apartments and luxury homes.",
    provider: "Studio Coral",
    rating: 4.8,
    reviews: 96,
    verified: true,
    topRated: true,
    availableWeek: true,
    image:
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
    lat: 25.7617,
    lng: -80.1918,
    publishedAt: "2026-08-18",
  },
  {
    id: "s3",
    category: "services",
    title: "Property Management",
    type: "management",
    pricing: "month",
    price: 150,
    currency: "EUR",
    country: "Portugal",
    state: "Lisboa",
    city: "Lisbon",
    description: "Tenant, rent and maintenance management for owners.",
    provider: "Alfama Property Care",
    rating: 4.9,
    reviews: 178,
    verified: true,
    topRated: true,
    availableWeek: true,
    online: true,
    image:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80",
    lat: 38.7223,
    lng: -9.1393,
    publishedAt: "2026-08-16",
  },
  {
    id: "s4",
    category: "services",
    title: "Renovation & Construction",
    type: "renovation",
    pricing: "quote",
    currency: "USD",
    country: "United Arab Emirates",
    state: "DU",
    city: "Dubai",
    description: "Turnkey renovation for residential and investment units.",
    provider: "Gulf Build Studio",
    rating: 4.7,
    reviews: 64,
    verified: true,
    availableWeek: true,
    image:
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80",
    lat: 25.2048,
    lng: 55.2708,
    publishedAt: "2026-08-12",
  },
  {
    id: "s5",
    category: "services",
    title: "Real Estate Agents",
    type: "agents",
    pricing: "quote",
    currency: "BRL",
    country: "Brasil",
    state: "RJ",
    city: "Rio de Janeiro",
    description: "Local agents for buying, selling and renting.",
    provider: "Costa Azul Brokers",
    rating: 4.8,
    reviews: 312,
    verified: true,
    availableToday: true,
    image:
      "https://images.unsplash.com/photo-1560520653-9e0d1c55bbfc?auto=format&fit=crop&w=1200&q=80",
    lat: -22.9068,
    lng: -43.1729,
    publishedAt: "2026-08-14",
  },
  {
    id: "s6",
    category: "services",
    title: "Architecture",
    type: "architecture",
    pricing: "from",
    price: 2800,
    currency: "BRL",
    country: "Brasil",
    state: "SP",
    city: "São Paulo",
    description: "Architectural design for homes and renovations.",
    provider: "Atelier Norte",
    rating: 4.9,
    reviews: 81,
    verified: true,
    topRated: true,
    image:
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80",
    lat: -23.5614,
    lng: -46.6558,
    publishedAt: "2026-08-10",
  },
  {
    id: "s7",
    category: "services",
    title: "Moving & Relocation",
    type: "moving",
    pricing: "from",
    price: 890,
    currency: "BRL",
    country: "Brasil",
    state: "SP",
    city: "Campinas",
    description: "Residential moving with packing and insurance.",
    provider: "Move Fácil",
    rating: 4.6,
    reviews: 143,
    verified: true,
    availableToday: true,
    availableWeek: true,
    image:
      "https://images.unsplash.com/photo-1600518464441-9154a64cb3c6?auto=format&fit=crop&w=1200&q=80",
    lat: -22.9056,
    lng: -47.0608,
    publishedAt: "2026-08-09",
  },
  {
    id: "s8",
    category: "services",
    title: "Insurance",
    type: "insurance",
    pricing: "from",
    price: 89,
    currency: "USD",
    country: "United States",
    state: "FL",
    city: "Orlando",
    description: "Home and rental insurance for property owners.",
    provider: "Harbor Cover",
    rating: 4.7,
    reviews: 205,
    verified: true,
    online: true,
    image:
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
    lat: 28.5383,
    lng: -81.3792,
    publishedAt: "2026-08-08",
  },
  {
    id: "s9",
    category: "services",
    title: "Mortgage / Financing",
    type: "financing",
    pricing: "quote",
    currency: "BRL",
    country: "Brasil",
    state: "SP",
    city: "São Paulo",
    description: "Mortgage options for buyers and investors.",
    provider: "Crédito Habitat",
    rating: 4.8,
    reviews: 127,
    verified: true,
    online: true,
    availableWeek: true,
    image:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
    lat: -23.567,
    lng: -46.693,
    publishedAt: "2026-08-07",
  },
  {
    id: "s10",
    category: "services",
    title: "Legal Services",
    type: "legal",
    pricing: "from",
    price: 650,
    currency: "BRL",
    country: "Brasil",
    state: "RS",
    city: "Porto Alegre",
    description: "Contracts, due diligence and closing support.",
    provider: "Vale Jurídico",
    rating: 4.9,
    reviews: 74,
    verified: true,
    online: true,
    image:
      "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80",
    lat: -30.0346,
    lng: -51.2177,
    publishedAt: "2026-08-06",
  },
  {
    id: "s11",
    category: "services",
    title: "Appraisal / Valuation",
    type: "appraisal",
    pricing: "from",
    price: 380,
    currency: "EUR",
    country: "Portugal",
    state: "Lisboa",
    city: "Lisbon",
    description: "Independent valuation for purchase and financing.",
    provider: "Lusitania Appraisal",
    rating: 4.8,
    reviews: 59,
    verified: true,
    availableWeek: true,
    image:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80",
    lat: 38.71,
    lng: -9.14,
    publishedAt: "2026-08-05",
  },
  {
    id: "s12",
    category: "services",
    title: "Photography / Virtual Tours",
    type: "photography",
    pricing: "from",
    price: 320,
    currency: "USD",
    country: "United States",
    state: "FL",
    city: "Miami",
    description: "Listing photos, video and 3D tours.",
    provider: "Lens & Key",
    rating: 4.9,
    reviews: 188,
    verified: true,
    topRated: true,
    availableToday: true,
    image:
      "https://images.unsplash.com/photo-1484154213498-4dd8d629d2c0?auto=format&fit=crop&w=1200&q=80",
    lat: 25.801,
    lng: -80.199,
    publishedAt: "2026-08-19",
  },
  {
    id: "s13",
    category: "services",
    title: "Home Staging",
    type: "staging",
    pricing: "from",
    price: 900,
    currency: "USD",
    country: "United States",
    state: "FL",
    city: "Orlando",
    description: "Staging to sell or rent faster.",
    provider: "Stage Right",
    rating: 4.7,
    reviews: 42,
    verified: true,
    availableWeek: true,
    image:
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80",
    lat: 28.54,
    lng: -81.38,
    publishedAt: "2026-08-04",
  },
  {
    id: "s14",
    category: "services",
    title: "Cleaning",
    type: "cleaning",
    pricing: "from",
    price: 180,
    currency: "BRL",
    country: "Brasil",
    state: "PR",
    city: "Curitiba",
    description: "Move-in, move-out and recurring property cleaning.",
    provider: "Casa Limpa",
    rating: 4.6,
    reviews: 231,
    verified: true,
    availableToday: true,
    image:
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",
    lat: -25.4284,
    lng: -49.2733,
    publishedAt: "2026-08-03",
  },
  {
    id: "s15",
    category: "services",
    title: "Maintenance & Repairs",
    type: "maintenance",
    pricing: "from",
    price: 220,
    currency: "BRL",
    country: "Brasil",
    state: "MG",
    city: "Belo Horizonte",
    description: "Plumbing, electrical and general property repairs.",
    provider: "Fix Habitat",
    rating: 4.5,
    reviews: 167,
    verified: true,
    availableToday: true,
    availableWeek: true,
    image:
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",
    lat: -19.9167,
    lng: -43.9345,
    publishedAt: "2026-08-02",
  },
  {
    id: "s16",
    category: "services",
    title: "Security",
    type: "security",
    pricing: "month",
    price: 89,
    currency: "USD",
    country: "United Arab Emirates",
    state: "DU",
    city: "Dubai",
    description: "Monitoring and security for homes and buildings.",
    provider: "SafeNest",
    rating: 4.8,
    reviews: 91,
    verified: true,
    online: true,
    image:
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1200&q=80",
    lat: 25.1124,
    lng: 55.139,
    publishedAt: "2026-08-01",
  },
  {
    id: "s17",
    category: "services",
    title: "Landscaping",
    type: "landscaping",
    pricing: "from",
    price: 750,
    currency: "EUR",
    country: "Portugal",
    state: "Lisboa",
    city: "Lisbon",
    description: "Gardens and outdoor spaces for residential properties.",
    provider: "Verde Atlântico",
    rating: 4.7,
    reviews: 38,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1200&q=80",
    lat: 38.697,
    lng: -9.421,
    publishedAt: "2026-07-28",
  },
  {
    id: "s18",
    category: "services",
    title: "Construction",
    type: "construction",
    pricing: "quote",
    currency: "BRL",
    country: "Brasil",
    state: "SC",
    city: "Florianópolis",
    description: "New builds and structural work for residential plots.",
    provider: "Serra Construtora",
    rating: 4.6,
    reviews: 27,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=80",
    lat: -27.5954,
    lng: -48.548,
    publishedAt: "2026-07-22",
  },
];
