import type { ProjectListing } from "./types";

export const projectListings: ProjectListing[] = [
  {
    id: "pj1",
    category: "projects",
    title: "Vista Marina Residence",
    type: "residential",
    status: "prelaunch",
    unitType: "apartments",
    bedsMin: 1,
    bedsMax: 4,
    price: 450000,
    currency: "USD",
    country: "United States",
    state: "FL",
    city: "Miami",
    neighborhood: "Brickell",
    developer: "Oceanic Development",
    delivery: "Q4 2027",
    deliveryYear: 2027,
    paymentPlan: true,
    highRoi: true,
    sustainable: false,
    luxury: true,
    amenities: true,
    verified: true,
    featured: true,
    image:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    lat: 25.7617,
    lng: -80.1918,
    publishedAt: "2026-08-18",
  },
  {
    id: "pj2",
    category: "projects",
    title: "Horizon Gardens",
    type: "residential",
    status: "construction",
    unitType: "apartments",
    bedsMin: 2,
    bedsMax: 3,
    price: 890000,
    currency: "BRL",
    country: "Brasil",
    state: "SP",
    city: "São Paulo",
    neighborhood: "Itaim Bibi",
    developer: "Horizon Incorporadora",
    delivery: "Q2 2028",
    deliveryYear: 2028,
    paymentPlan: true,
    highRoi: false,
    sustainable: true,
    luxury: false,
    amenities: true,
    verified: true,
    featured: true,
    image:
      "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80",
    lat: -23.585,
    lng: -46.675,
    publishedAt: "2026-08-12",
  },
  {
    id: "pj3",
    category: "projects",
    title: "Alfama Riverside",
    type: "mixed",
    status: "ready",
    unitType: "apartments",
    bedsMin: 1,
    bedsMax: 3,
    price: 380000,
    currency: "EUR",
    country: "Portugal",
    state: "Lisboa",
    city: "Lisbon",
    neighborhood: "Alfama",
    developer: "Lusitania Homes",
    delivery: "Q3 2026",
    deliveryYear: 2026,
    paymentPlan: false,
    highRoi: true,
    sustainable: true,
    luxury: false,
    amenities: true,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1544989164-31dc3c645987?auto=format&fit=crop&w=1200&q=80",
    lat: 38.711,
    lng: -9.129,
    publishedAt: "2026-07-28",
  },
  {
    id: "pj4",
    category: "projects",
    title: "Orlando Lake Residences",
    type: "residential",
    status: "prelaunch",
    unitType: "houses",
    bedsMin: 3,
    bedsMax: 5,
    price: 520000,
    currency: "USD",
    country: "United States",
    state: "FL",
    city: "Orlando",
    neighborhood: "Lake Nona",
    developer: "Sunbelt Partners",
    delivery: "Q1 2028",
    deliveryYear: 2028,
    paymentPlan: true,
    highRoi: true,
    sustainable: false,
    luxury: false,
    amenities: true,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    lat: 28.373,
    lng: -81.285,
    publishedAt: "2026-08-20",
  },
  {
    id: "pj5",
    category: "projects",
    title: "Marina Bay Towers",
    type: "residential",
    status: "construction",
    unitType: "apartments",
    bedsMin: 1,
    bedsMax: 3,
    price: 720000,
    currency: "USD",
    country: "United Arab Emirates",
    state: "DU",
    city: "Dubai",
    neighborhood: "Dubai Marina",
    developer: "Gulf Horizon",
    delivery: "Q4 2027",
    deliveryYear: 2027,
    paymentPlan: true,
    highRoi: true,
    sustainable: false,
    luxury: true,
    amenities: true,
    verified: true,
    premium: true,
    featured: true,
    image:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
    lat: 25.0805,
    lng: 55.1403,
    publishedAt: "2026-08-08",
  },
  {
    id: "pj6",
    category: "projects",
    title: "Copacabana Skyline",
    type: "residential",
    status: "construction",
    unitType: "apartments",
    bedsMin: 2,
    bedsMax: 4,
    price: 1850000,
    currency: "BRL",
    country: "Brasil",
    state: "RJ",
    city: "Rio de Janeiro",
    neighborhood: "Copacabana",
    developer: "Atlântica Incorporações",
    delivery: "Q3 2028",
    deliveryYear: 2028,
    paymentPlan: true,
    highRoi: false,
    sustainable: false,
    luxury: true,
    amenities: true,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&w=1200&q=80",
    lat: -22.9711,
    lng: -43.1822,
    publishedAt: "2026-07-15",
  },
  {
    id: "pj7",
    category: "projects",
    title: "Business Hub Paulista",
    type: "commercial",
    status: "prelaunch",
    unitType: "offices",
    price: 980000,
    currency: "BRL",
    country: "Brasil",
    state: "SP",
    city: "São Paulo",
    neighborhood: "Bela Vista",
    developer: "Paulista Offices",
    delivery: "Q2 2029",
    deliveryYear: 2029,
    paymentPlan: true,
    highRoi: true,
    sustainable: true,
    luxury: false,
    amenities: true,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    lat: -23.5614,
    lng: -46.6558,
    publishedAt: "2026-08-10",
  },
  {
    id: "pj8",
    category: "projects",
    title: "Green District Eco",
    type: "mixed",
    status: "construction",
    unitType: "apartments",
    bedsMin: 1,
    bedsMax: 2,
    price: 620000,
    currency: "BRL",
    country: "Brasil",
    state: "PR",
    city: "Curitiba",
    neighborhood: "Batel",
    developer: "EcoUrban",
    delivery: "Q1 2027",
    deliveryYear: 2027,
    paymentPlan: true,
    highRoi: false,
    sustainable: true,
    luxury: false,
    amenities: true,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&w=1200&q=80",
    lat: -25.439,
    lng: -49.276,
    publishedAt: "2026-06-30",
  },
  {
    id: "pj9",
    category: "projects",
    title: "Porto Alegre Lofts",
    type: "residential",
    status: "ready",
    unitType: "studios",
    bedsMin: 1,
    bedsMax: 1,
    price: 410000,
    currency: "BRL",
    country: "Brasil",
    state: "RS",
    city: "Porto Alegre",
    neighborhood: "Moinhos de Vento",
    developer: "Sul Desenvolvimento",
    delivery: "Q2 2026",
    deliveryYear: 2026,
    paymentPlan: false,
    highRoi: false,
    sustainable: false,
    luxury: false,
    amenities: false,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    lat: -30.0277,
    lng: -51.2287,
    publishedAt: "2026-05-20",
  },
  {
    id: "pj10",
    category: "projects",
    title: "Lisbon Atlantic Villas",
    type: "hospitality",
    status: "prelaunch",
    unitType: "villas",
    bedsMin: 3,
    bedsMax: 6,
    price: 890000,
    currency: "EUR",
    country: "Portugal",
    state: "Lisboa",
    city: "Lisbon",
    neighborhood: "Cascais",
    developer: "Atlantic Estates",
    delivery: "Q4 2028",
    deliveryYear: 2028,
    paymentPlan: true,
    highRoi: true,
    sustainable: true,
    luxury: true,
    amenities: true,
    verified: true,
    premium: true,
    image:
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    lat: 38.697,
    lng: -9.421,
    publishedAt: "2026-08-19",
  },
  {
    id: "pj11",
    category: "projects",
    title: "Logistics Park Campinas",
    type: "industrial",
    status: "construction",
    unitType: "offices",
    price: 2400000,
    currency: "BRL",
    country: "Brasil",
    state: "SP",
    city: "Campinas",
    developer: "Inland Parks",
    delivery: "Q3 2027",
    deliveryYear: 2027,
    paymentPlan: true,
    highRoi: true,
    sustainable: true,
    luxury: false,
    amenities: false,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    lat: -22.9056,
    lng: -47.0608,
    publishedAt: "2026-07-02",
  },
  {
    id: "pj12",
    category: "projects",
    title: "Barra Lifestyle",
    type: "residential",
    status: "prelaunch",
    unitType: "apartments",
    bedsMin: 2,
    bedsMax: 4,
    price: 760000,
    currency: "BRL",
    country: "Brasil",
    state: "RJ",
    city: "Rio de Janeiro",
    neighborhood: "Barra da Tijuca",
    developer: "Costa Azul",
    delivery: "Q1 2029",
    deliveryYear: 2029,
    paymentPlan: true,
    highRoi: false,
    sustainable: false,
    luxury: true,
    amenities: true,
    verified: true,
    featured: true,
    image:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    lat: -23.004,
    lng: -43.365,
    publishedAt: "2026-08-21",
  },
  {
    id: "pj13",
    category: "projects",
    title: "Wynwood Collective",
    type: "mixed",
    status: "construction",
    unitType: "studios",
    bedsMin: 1,
    bedsMax: 2,
    price: 310000,
    currency: "USD",
    country: "United States",
    state: "FL",
    city: "Miami",
    neighborhood: "Wynwood",
    developer: "Collective Urban",
    delivery: "Q2 2027",
    deliveryYear: 2027,
    paymentPlan: true,
    highRoi: true,
    sustainable: true,
    luxury: false,
    amenities: true,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    lat: 25.801,
    lng: -80.199,
    publishedAt: "2026-06-18",
  },
  {
    id: "pj14",
    category: "projects",
    title: "Residencial Horizon",
    type: "residential",
    status: "prelaunch",
    unitType: "apartments",
    bedsMin: 3,
    bedsMax: 3,
    price: 720000,
    currency: "BRL",
    country: "Brasil",
    state: "SC",
    city: "Florianópolis",
    neighborhood: "Jurerê",
    developer: "Horizon Incorporadora",
    delivery: "Q4 2027",
    deliveryYear: 2027,
    paymentPlan: true,
    highRoi: false,
    sustainable: false,
    luxury: false,
    amenities: true,
    verified: true,
    featured: true,
    propertyId: "p8",
    image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    lat: -27.439,
    lng: -48.498,
    publishedAt: "2026-08-14",
  },
  {
    id: "pj15",
    category: "projects",
    title: "Downtown Orlando Suites",
    type: "hospitality",
    status: "ready",
    unitType: "studios",
    bedsMin: 1,
    bedsMax: 1,
    price: 275000,
    currency: "USD",
    country: "United States",
    state: "FL",
    city: "Orlando",
    neighborhood: "Downtown",
    developer: "StayCap",
    delivery: "Q1 2026",
    deliveryYear: 2026,
    paymentPlan: false,
    highRoi: true,
    sustainable: false,
    luxury: false,
    amenities: true,
    verified: true,
    image:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
    lat: 28.5383,
    lng: -81.3792,
    publishedAt: "2026-04-12",
  },
  {
    id: "pj16",
    category: "projects",
    title: "Palm Jumeirah Estate",
    type: "residential",
    status: "construction",
    unitType: "villas",
    bedsMin: 4,
    bedsMax: 6,
    price: 2400000,
    currency: "USD",
    country: "United Arab Emirates",
    state: "DU",
    city: "Dubai",
    neighborhood: "Palm Jumeirah",
    developer: "Gulf Horizon",
    delivery: "Q3 2028",
    deliveryYear: 2028,
    paymentPlan: true,
    highRoi: false,
    sustainable: false,
    luxury: true,
    amenities: true,
    verified: true,
    premium: true,
    image:
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80",
    lat: 25.1124,
    lng: 55.139,
    publishedAt: "2026-07-22",
  },
];
