import { slugifyCompanyId } from "@/lib/leads/utils";
import type { BrokerProfile } from "./types";

const COVER_CITY =
  "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80";
const COVER_COAST =
  "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1400&q=80";
const COVER_VINEYARD =
  "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=80";
const COVER_LISBON =
  "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1400&q=80";
const COVER_MIAMI =
  "https://images.unsplash.com/photo-1535498730771-e735b998cd64?auto=format&fit=crop&w=1400&q=80";

export const mockBrokers: BrokerProfile[] = [
  {
    id: "br-ana-castro",
    name: "Ana Castro",
    role: "Corretora de imóveis",
    bio: "Especialista em residencial de alto padrão na Serra Gaúcha. Acompanha o cliente da busca até a escritura, com foco em casas e condomínios.",
    photo:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    coverImage: COVER_VINEYARD,
    creci: "RS 48.221-F",
    companyId: slugifyCompanyId("RSC Imóveis"),
    companyName: "RSC Imóveis",
    companyLogo: "",
    verified: true,
    country: "Brasil",
    state: "RS",
    city: "Bento Gonçalves",
    languages: ["PT", "ES", "EN"],
    specialties: ["residential", "luxury", "newDevelopments"],
    phone: "+55 54 99912-4401",
    whatsapp: "5554999124401",
    email: "ana.castro@rscimoveis.com",
    rating: 4.9,
    reviewsCount: 86,
    listingsCount: 24,
    yearsActive: 11,
    soldCount: 190,
  },
  {
    id: "br-lucas-mendes",
    name: "Lucas Mendes",
    role: "Corretor associado",
    bio: "Atua com lançamentos e investimento em Porto Alegre. Conecta compradores a imóveis verificados e negocia condições com as construtoras.",
    photo:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80",
    coverImage: COVER_CITY,
    creci: "RS 52.104-F",
    companyId: slugifyCompanyId("POA Living"),
    companyName: "POA Living",
    companyLogo: "",
    verified: true,
    country: "Brasil",
    state: "RS",
    city: "Porto Alegre",
    languages: ["PT", "EN"],
    specialties: ["newDevelopments", "investment", "residential"],
    phone: "+55 51 98821-3308",
    whatsapp: "5551988213308",
    email: "lucas.mendes@poaliving.com",
    rating: 4.8,
    reviewsCount: 64,
    listingsCount: 18,
    yearsActive: 8,
    soldCount: 132,
  },
  {
    id: "br-marina-souza",
    name: "Marina Souza",
    role: "Corretora comercial",
    bio: "Foco em salas, lojas e galpões no Vale dos Vinhedos. Ajuda empresas a encontrar ponto comercial com retorno e localização estratégica.",
    photo:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
    coverImage: COVER_CITY,
    creci: "RS 41.887-F",
    companyId: slugifyCompanyId("Vale Imóveis"),
    companyName: "Vale Imóveis",
    companyLogo: "",
    verified: true,
    country: "Brasil",
    state: "RS",
    city: "Caxias do Sul",
    languages: ["PT", "ES"],
    specialties: ["commercial", "investment"],
    phone: "+55 54 99103-7720",
    whatsapp: "5554991037720",
    email: "marina.souza@valeimoveis.com",
    rating: 4.7,
    reviewsCount: 41,
    listingsCount: 15,
    yearsActive: 9,
    soldCount: 98,
  },
  {
    id: "br-rafael-oliveira",
    name: "Rafael Oliveira",
    role: "Consultor imobiliário",
    bio: "Trabalha com terrenos e incorporação. Orienta investidores em áreas de expansão e acompanha o processo de due diligence.",
    photo:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    coverImage: COVER_VINEYARD,
    creci: "RS 39.512-F",
    companyId: slugifyCompanyId("Serra Terras"),
    companyName: "Serra Terras",
    companyLogo: "",
    verified: true,
    country: "Brasil",
    state: "RS",
    city: "Gramado",
    languages: ["PT", "EN"],
    specialties: ["investment", "newDevelopments"],
    phone: "+55 54 99977-2104",
    whatsapp: "5554999772104",
    email: "rafael.oliveira@serraterras.com",
    rating: 4.6,
    reviewsCount: 33,
    listingsCount: 12,
    yearsActive: 7,
    soldCount: 74,
  },
  {
    id: "br-camila-ferreira",
    name: "Camila Ferreira",
    role: "Corretora premium",
    bio: "Especialista em penthouses e casas de praia. Atende compradores que buscam imóveis com vista, acabamento alto e privacidade.",
    photo:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    coverImage: COVER_COAST,
    creci: "RJ 28.440-F",
    companyId: slugifyCompanyId("RSC Imóveis Premium"),
    companyName: "RSC Imóveis Premium",
    companyLogo: "",
    verified: true,
    country: "Brasil",
    state: "RJ",
    city: "Rio de Janeiro",
    languages: ["PT", "EN", "ES"],
    specialties: ["luxury", "residential"],
    phone: "+55 21 98840-1190",
    whatsapp: "5521988401190",
    email: "camila.ferreira@rscpremium.com",
    rating: 4.9,
    reviewsCount: 112,
    listingsCount: 21,
    yearsActive: 14,
    soldCount: 248,
  },
  {
    id: "br-diego-almeida",
    name: "Diego Almeida",
    role: "Corretor locação",
    bio: "Gestão de aluguel residencial e sazonal. Cuida de visitas, contratos e inquilinos para proprietários que querem renda recorrente.",
    photo:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    coverImage: COVER_CITY,
    creci: "SP 176.902-F",
    companyId: slugifyCompanyId("Metro Living"),
    companyName: "Metro Living",
    companyLogo: "",
    verified: false,
    country: "Brasil",
    state: "SP",
    city: "São Paulo",
    languages: ["PT", "EN"],
    specialties: ["rentals", "residential"],
    phone: "+55 11 97654-8821",
    whatsapp: "5511976548821",
    email: "diego.almeida@metroliving.com",
    rating: 4.5,
    reviewsCount: 29,
    listingsCount: 16,
    yearsActive: 5,
    soldCount: 40,
  },
  {
    id: "pt-sofia-nunes",
    name: "Sofia Nunes",
    role: "Consultora imobiliária",
    bio: "Ajuda brasileiros e europeus a comprar em Lisboa e Cascais. Conhece o mercado de golden visa, reabilitação e apartamentos no centro.",
    photo:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80",
    coverImage: COVER_LISBON,
    creci: "AMI 15120",
    companyId: slugifyCompanyId("Lisboa Urban"),
    companyName: "Lisboa Urban",
    companyLogo: "",
    verified: true,
    country: "Portugal",
    state: "Lisboa",
    city: "Lisboa",
    languages: ["PT", "EN", "ES"],
    specialties: ["residential", "investment", "luxury"],
    phone: "+351 912 440 118",
    whatsapp: "351912440118",
    email: "sofia.nunes@lisboaurban.pt",
    rating: 4.8,
    reviewsCount: 57,
    listingsCount: 14,
    yearsActive: 10,
    soldCount: 121,
  },
  {
    id: "us-james-carter",
    name: "James Carter",
    role: "Licensed realtor",
    bio: "Miami and Orlando specialist for international buyers. Focuses on waterfront condos, new construction and relocation packages.",
    photo:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    coverImage: COVER_MIAMI,
    creci: "FL 3478210",
    companyId: slugifyCompanyId("Sunshine Homes"),
    companyName: "Sunshine Homes",
    companyLogo: "",
    verified: true,
    country: "United States",
    state: "FL",
    city: "Miami",
    languages: ["EN", "ES", "PT"],
    specialties: ["luxury", "newDevelopments", "residential"],
    phone: "+1 305 555-0148",
    whatsapp: "13055550148",
    email: "james.carter@sunshinehomes.com",
    rating: 4.7,
    reviewsCount: 73,
    listingsCount: 19,
    yearsActive: 12,
    soldCount: 167,
  },
  {
    id: "ae-layla-hassan",
    name: "Layla Hassan",
    role: "Property consultant",
    bio: "Guides investors through Dubai off-plan and ready homes. Transparent about fees, yields and developer delivery timelines.",
    photo:
      "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=400&q=80",
    coverImage: COVER_CITY,
    creci: "RERA 45821",
    companyId: slugifyCompanyId("Gulf Prestige"),
    companyName: "Gulf Prestige",
    companyLogo: "",
    verified: true,
    country: "United Arab Emirates",
    state: "Dubai",
    city: "Dubai",
    languages: ["EN", "AR", "PT"],
    specialties: ["investment", "luxury", "newDevelopments"],
    phone: "+971 50 123 4408",
    whatsapp: "971501234408",
    email: "layla.hassan@gulfprestige.ae",
    rating: 4.8,
    reviewsCount: 48,
    listingsCount: 11,
    yearsActive: 6,
    soldCount: 89,
  },
];
