import type { Locale, MarketConfig, MarketId, MarketRegion } from "./types";

const baseNavLinks = {
  properties: { href: "/imoveis", label: "properties" },
  vehicles: { href: "/veiculos", label: "vehicles" },
  credit: { href: "/financing", label: "credit" },
  business: {
    href: "/para-empresas",
    label: "paraEmpresas",
    highlight: true,
    icon: "business" as const,
  },
  help: { href: "/help", label: "help" },
} as const;

function navLinks(credit = false) {
  const links = [
    baseNavLinks.properties,
    baseNavLinks.vehicles,
    ...(credit ? [baseNavLinks.credit] : []),
    baseNavLinks.business,
    baseNavLinks.help,
  ];
  return [...links];
}

type MarketSeed = Omit<MarketConfig, "nameKey">;

function m(seed: MarketSeed): MarketConfig {
  return { ...seed, nameKey: `markets.names.${seed.id}` };
}

/** bbox: minLon, minLat, maxLon, maxLat */
export const marketDefinitions: Record<MarketId, MarketConfig> = {
  // —— LATAM ——
  br: m({
    id: "br",
    region: "latam",
    flag: "🇧🇷",
    defaultLocale: "pt",
    currency: { code: "BRL", symbol: "R$" },
    countryName: "Brasil",
    countryCode: "br",
    creditAvailable: true,
    navLinks: navLinks(true),
    geocodeLang: "pt",
    geocodeBbox: [-74, -33.8, -32, 5.5],
  }),
  mx: m({
    id: "mx",
    region: "latam",
    flag: "🇲🇽",
    defaultLocale: "es",
    currency: { code: "MXN", symbol: "$" },
    countryName: "México",
    countryCode: "mx",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-118.4, 14.5, -86.7, 32.7],
  }),
  ar: m({
    id: "ar",
    region: "latam",
    flag: "🇦🇷",
    defaultLocale: "es",
    currency: { code: "ARS", symbol: "$" },
    countryName: "Argentina",
    countryCode: "ar",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-73.6, -55.2, -53.5, -21.8],
  }),
  co: m({
    id: "co",
    region: "latam",
    flag: "🇨🇴",
    defaultLocale: "es",
    currency: { code: "COP", symbol: "$" },
    countryName: "Colombia",
    countryCode: "co",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-79.1, -4.2, -66.9, 13.5],
  }),
  cl: m({
    id: "cl",
    region: "latam",
    flag: "🇨🇱",
    defaultLocale: "es",
    currency: { code: "CLP", symbol: "$" },
    countryName: "Chile",
    countryCode: "cl",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-75.7, -56, -66.4, -17.5],
  }),
  pe: m({
    id: "pe",
    region: "latam",
    flag: "🇵🇪",
    defaultLocale: "es",
    currency: { code: "PEN", symbol: "S/" },
    countryName: "Perú",
    countryCode: "pe",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-81.4, -18.4, -68.7, -0.04],
  }),
  uy: m({
    id: "uy",
    region: "latam",
    flag: "🇺🇾",
    defaultLocale: "es",
    currency: { code: "UYU", symbol: "$" },
    countryName: "Uruguay",
    countryCode: "uy",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-58.5, -35, -53.1, -30.1],
  }),
  ec: m({
    id: "ec",
    region: "latam",
    flag: "🇪🇨",
    defaultLocale: "es",
    currency: { code: "USD", symbol: "$" },
    countryName: "Ecuador",
    countryCode: "ec",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-81.1, -5, -75.2, 1.7],
  }),
  ve: m({
    id: "ve",
    region: "latam",
    flag: "🇻🇪",
    defaultLocale: "es",
    currency: { code: "USD", symbol: "$" },
    countryName: "Venezuela",
    countryCode: "ve",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-73.4, 0.6, -59.8, 12.5],
  }),
  bo: m({
    id: "bo",
    region: "latam",
    flag: "🇧🇴",
    defaultLocale: "es",
    currency: { code: "BOB", symbol: "Bs" },
    countryName: "Bolivia",
    countryCode: "bo",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-69.6, -22.9, -57.5, -9.7],
  }),
  py: m({
    id: "py",
    region: "latam",
    flag: "🇵🇾",
    defaultLocale: "es",
    currency: { code: "PYG", symbol: "₲" },
    countryName: "Paraguay",
    countryCode: "py",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-62.6, -27.6, -54.3, -19.3],
  }),
  cr: m({
    id: "cr",
    region: "latam",
    flag: "🇨🇷",
    defaultLocale: "es",
    currency: { code: "CRC", symbol: "₡" },
    countryName: "Costa Rica",
    countryCode: "cr",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-85.9, 8, -82.5, 11.2],
  }),
  pa: m({
    id: "pa",
    region: "latam",
    flag: "🇵🇦",
    defaultLocale: "es",
    currency: { code: "PAB", symbol: "B/." },
    countryName: "Panamá",
    countryCode: "pa",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-83.1, 7.2, -77.2, 9.6],
  }),
  gt: m({
    id: "gt",
    region: "latam",
    flag: "🇬🇹",
    defaultLocale: "es",
    currency: { code: "GTQ", symbol: "Q" },
    countryName: "Guatemala",
    countryCode: "gt",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-92.3, 13.7, -88.2, 17.8],
  }),
  do: m({
    id: "do",
    region: "latam",
    flag: "🇩🇴",
    defaultLocale: "es",
    currency: { code: "DOP", symbol: "RD$" },
    countryName: "República Dominicana",
    countryCode: "do",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-72, 17.5, -68.3, 19.9],
  }),
  cu: m({
    id: "cu",
    region: "latam",
    flag: "🇨🇺",
    defaultLocale: "es",
    currency: { code: "CUP", symbol: "$" },
    countryName: "Cuba",
    countryCode: "cu",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-84.9, 19.8, -74.1, 23.3],
  }),
  hn: m({
    id: "hn",
    region: "latam",
    flag: "🇭🇳",
    defaultLocale: "es",
    currency: { code: "HNL", symbol: "L" },
    countryName: "Honduras",
    countryCode: "hn",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-89.4, 12.9, -83.1, 16.5],
  }),
  sv: m({
    id: "sv",
    region: "latam",
    flag: "🇸🇻",
    defaultLocale: "es",
    currency: { code: "USD", symbol: "$" },
    countryName: "El Salvador",
    countryCode: "sv",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-90.1, 13.1, -87.7, 14.4],
  }),
  ni: m({
    id: "ni",
    region: "latam",
    flag: "🇳🇮",
    defaultLocale: "es",
    currency: { code: "NIO", symbol: "C$" },
    countryName: "Nicaragua",
    countryCode: "ni",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-87.7, 10.7, -82.7, 15],
  }),

  // —— North America ——
  us: m({
    id: "us",
    region: "north_america",
    flag: "🇺🇸",
    defaultLocale: "en",
    currency: { code: "USD", symbol: "$" },
    countryName: "United States",
    countryCode: "us",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [-125, 24.5, -66.9, 49.5],
  }),
  ca: m({
    id: "ca",
    region: "north_america",
    flag: "🇨🇦",
    defaultLocale: "en",
    currency: { code: "CAD", symbol: "C$" },
    countryName: "Canada",
    countryCode: "ca",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [-141, 41.7, -52.6, 83.1],
  }),

  // —— Caribbean ——
  jm: m({
    id: "jm",
    region: "caribbean",
    flag: "🇯🇲",
    defaultLocale: "en",
    currency: { code: "JMD", symbol: "J$" },
    countryName: "Jamaica",
    countryCode: "jm",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [-78.4, 17.7, -76.2, 18.5],
  }),
  pr: m({
    id: "pr",
    region: "caribbean",
    flag: "🇵🇷",
    defaultLocale: "es",
    currency: { code: "USD", symbol: "$" },
    countryName: "Puerto Rico",
    countryCode: "pr",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-67.9, 17.9, -65.2, 18.5],
  }),
  tt: m({
    id: "tt",
    region: "caribbean",
    flag: "🇹🇹",
    defaultLocale: "en",
    currency: { code: "TTD", symbol: "TT$" },
    countryName: "Trinidad y Tobago",
    countryCode: "tt",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [-61.9, 10, -60.5, 11.4],
  }),
  ht: m({
    id: "ht",
    region: "caribbean",
    flag: "🇭🇹",
    defaultLocale: "en",
    currency: { code: "HTG", symbol: "G" },
    countryName: "Haití",
    countryCode: "ht",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "fr",
    geocodeBbox: [-74.5, 18, -71.6, 20.1],
  }),
  bs: m({
    id: "bs",
    region: "caribbean",
    flag: "🇧🇸",
    defaultLocale: "en",
    currency: { code: "BSD", symbol: "$" },
    countryName: "Bahamas",
    countryCode: "bs",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [-80.5, 20.9, -72.7, 27.3],
  }),
  bb: m({
    id: "bb",
    region: "caribbean",
    flag: "🇧🇧",
    defaultLocale: "en",
    currency: { code: "BBD", symbol: "$" },
    countryName: "Barbados",
    countryCode: "bb",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [-59.7, 13, -59.4, 13.3],
  }),

  // —— Europe ——
  es: m({
    id: "es",
    region: "europe",
    flag: "🇪🇸",
    defaultLocale: "es",
    currency: { code: "EUR", symbol: "€" },
    countryName: "España",
    countryCode: "es",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "es",
    geocodeBbox: [-9.6, 36, 4.5, 43.9],
  }),
  pt: m({
    id: "pt",
    region: "europe",
    flag: "🇵🇹",
    defaultLocale: "pt",
    currency: { code: "EUR", symbol: "€" },
    countryName: "Portugal",
    countryCode: "pt",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "pt",
    geocodeBbox: [-9.6, 36.8, -6, 42.2],
  }),
  fr: m({
    id: "fr",
    region: "europe",
    flag: "🇫🇷",
    defaultLocale: "en",
    currency: { code: "EUR", symbol: "€" },
    countryName: "France",
    countryCode: "fr",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "fr",
    geocodeBbox: [-5.2, 41, 9.7, 51.2],
  }),
  de: m({
    id: "de",
    region: "europe",
    flag: "🇩🇪",
    defaultLocale: "en",
    currency: { code: "EUR", symbol: "€" },
    countryName: "Germany",
    countryCode: "de",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "de",
    geocodeBbox: [5.9, 47.3, 15, 55.1],
  }),
  it: m({
    id: "it",
    region: "europe",
    flag: "🇮🇹",
    defaultLocale: "en",
    currency: { code: "EUR", symbol: "€" },
    countryName: "Italy",
    countryCode: "it",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "it",
    geocodeBbox: [6.6, 36.6, 18.5, 47.1],
  }),
  gb: m({
    id: "gb",
    region: "europe",
    flag: "🇬🇧",
    defaultLocale: "en",
    currency: { code: "GBP", symbol: "£" },
    countryName: "United Kingdom",
    countryCode: "gb",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [-8.6, 49.9, 1.8, 60.9],
  }),
  ie: m({
    id: "ie",
    region: "europe",
    flag: "🇮🇪",
    defaultLocale: "en",
    currency: { code: "EUR", symbol: "€" },
    countryName: "Ireland",
    countryCode: "ie",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [-10.5, 51.4, -5.9, 55.4],
  }),
  nl: m({
    id: "nl",
    region: "europe",
    flag: "🇳🇱",
    defaultLocale: "en",
    currency: { code: "EUR", symbol: "€" },
    countryName: "Netherlands",
    countryCode: "nl",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "nl",
    geocodeBbox: [3.4, 50.7, 7.2, 53.6],
  }),
  be: m({
    id: "be",
    region: "europe",
    flag: "🇧🇪",
    defaultLocale: "en",
    currency: { code: "EUR", symbol: "€" },
    countryName: "Belgium",
    countryCode: "be",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "fr",
    geocodeBbox: [2.5, 49.5, 6.4, 51.5],
  }),
  ch: m({
    id: "ch",
    region: "europe",
    flag: "🇨🇭",
    defaultLocale: "en",
    currency: { code: "CHF", symbol: "CHF" },
    countryName: "Switzerland",
    countryCode: "ch",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "de",
    geocodeBbox: [5.9, 45.8, 10.5, 47.8],
  }),
  at: m({
    id: "at",
    region: "europe",
    flag: "🇦🇹",
    defaultLocale: "en",
    currency: { code: "EUR", symbol: "€" },
    countryName: "Austria",
    countryCode: "at",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "de",
    geocodeBbox: [9.5, 46.4, 17.2, 49],
  }),
  pl: m({
    id: "pl",
    region: "europe",
    flag: "🇵🇱",
    defaultLocale: "en",
    currency: { code: "PLN", symbol: "zł" },
    countryName: "Poland",
    countryCode: "pl",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "pl",
    geocodeBbox: [14.1, 49, 24.2, 54.8],
  }),
  se: m({
    id: "se",
    region: "europe",
    flag: "🇸🇪",
    defaultLocale: "en",
    currency: { code: "SEK", symbol: "kr" },
    countryName: "Sweden",
    countryCode: "se",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "sv",
    geocodeBbox: [11, 55.3, 24.2, 69.1],
  }),
  no: m({
    id: "no",
    region: "europe",
    flag: "🇳🇴",
    defaultLocale: "en",
    currency: { code: "NOK", symbol: "kr" },
    countryName: "Norway",
    countryCode: "no",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "no",
    geocodeBbox: [4.6, 57.9, 31.1, 71.2],
  }),
  gr: m({
    id: "gr",
    region: "europe",
    flag: "🇬🇷",
    defaultLocale: "en",
    currency: { code: "EUR", symbol: "€" },
    countryName: "Greece",
    countryCode: "gr",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "el",
    geocodeBbox: [19.4, 34.8, 29.6, 41.8],
  }),
  cz: m({
    id: "cz",
    region: "europe",
    flag: "🇨🇿",
    defaultLocale: "en",
    currency: { code: "CZK", symbol: "Kč" },
    countryName: "Czech Republic",
    countryCode: "cz",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "cs",
    geocodeBbox: [12.1, 48.5, 18.9, 51.1],
  }),
  ro: m({
    id: "ro",
    region: "europe",
    flag: "🇷🇴",
    defaultLocale: "en",
    currency: { code: "RON", symbol: "lei" },
    countryName: "Romania",
    countryCode: "ro",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "ro",
    geocodeBbox: [20.2, 43.6, 29.7, 48.3],
  }),

  // —— Africa ——
  za: m({
    id: "za",
    region: "africa",
    flag: "🇿🇦",
    defaultLocale: "en",
    currency: { code: "ZAR", symbol: "R" },
    countryName: "South Africa",
    countryCode: "za",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [16.5, -34.8, 32.9, -22.1],
  }),
  ng: m({
    id: "ng",
    region: "africa",
    flag: "🇳🇬",
    defaultLocale: "en",
    currency: { code: "NGN", symbol: "₦" },
    countryName: "Nigeria",
    countryCode: "ng",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [2.7, 4.3, 14.7, 13.9],
  }),
  ke: m({
    id: "ke",
    region: "africa",
    flag: "🇰🇪",
    defaultLocale: "en",
    currency: { code: "KES", symbol: "KSh" },
    countryName: "Kenya",
    countryCode: "ke",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [33.9, -4.7, 41.9, 5.5],
  }),
  gh: m({
    id: "gh",
    region: "africa",
    flag: "🇬🇭",
    defaultLocale: "en",
    currency: { code: "GHS", symbol: "₵" },
    countryName: "Ghana",
    countryCode: "gh",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [-3.3, 4.7, 1.2, 11.2],
  }),
  eg: m({
    id: "eg",
    region: "africa",
    flag: "🇪🇬",
    defaultLocale: "en",
    currency: { code: "EGP", symbol: "E£" },
    countryName: "Egypt",
    countryCode: "eg",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "ar",
    geocodeBbox: [24.7, 22, 36.9, 31.7],
  }),
  ma: m({
    id: "ma",
    region: "africa",
    flag: "🇲🇦",
    defaultLocale: "en",
    currency: { code: "MAD", symbol: "DH" },
    countryName: "Morocco",
    countryCode: "ma",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "fr",
    geocodeBbox: [-17.1, 21, -1, 35.9],
  }),
  ao: m({
    id: "ao",
    region: "africa",
    flag: "🇦🇴",
    defaultLocale: "pt",
    currency: { code: "AOA", symbol: "Kz" },
    countryName: "Angola",
    countryCode: "ao",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "pt",
    geocodeBbox: [11.7, -18, 24.1, -4.4],
  }),
  mz: m({
    id: "mz",
    region: "africa",
    flag: "🇲🇿",
    defaultLocale: "pt",
    currency: { code: "MZN", symbol: "MT" },
    countryName: "Mozambique",
    countryCode: "mz",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "pt",
    geocodeBbox: [30.2, -26.9, 40.8, -10.5],
  }),
  sn: m({
    id: "sn",
    region: "africa",
    flag: "🇸🇳",
    defaultLocale: "en",
    currency: { code: "XOF", symbol: "CFA" },
    countryName: "Senegal",
    countryCode: "sn",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "fr",
    geocodeBbox: [-17.5, 12.3, -11.3, 16.7],
  }),
  ci: m({
    id: "ci",
    region: "africa",
    flag: "🇨🇮",
    defaultLocale: "en",
    currency: { code: "XOF", symbol: "CFA" },
    countryName: "Côte d'Ivoire",
    countryCode: "ci",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "fr",
    geocodeBbox: [-8.6, 4.4, -2.5, 10.7],
  }),
  tz: m({
    id: "tz",
    region: "africa",
    flag: "🇹🇿",
    defaultLocale: "en",
    currency: { code: "TZS", symbol: "TSh" },
    countryName: "Tanzania",
    countryCode: "tz",
    creditAvailable: false,
    navLinks: navLinks(),
    geocodeLang: "en",
    geocodeBbox: [29.3, -11.7, 40.5, -0.9],
  }),
};

export const marketRegions: { id: MarketRegion; labelKey: string }[] = [
  { id: "latam", labelKey: "regions.latam" },
  { id: "north_america", labelKey: "regions.northAmerica" },
  { id: "caribbean", labelKey: "regions.caribbean" },
  { id: "europe", labelKey: "regions.europe" },
  { id: "africa", labelKey: "regions.africa" },
];

export const isoCountryToMarket: Record<string, MarketId> = Object.fromEntries(
  Object.values(marketDefinitions).map((market) => [
    market.countryCode.toUpperCase(),
    market.id,
  ]),
) as Record<string, MarketId>;
