"""French page content for REESKOVA corporate presentation."""
from reportlab.lib.units import mm

EMAIL = "rscgroupltda@gmail.com"
PHONE = "+33 7 85 61 86 44"
WEB = "www.rscchain.com"
CONTACT = f"{EMAIL} · {PHONE} · {WEB}"
W = 210 * mm  # unused placeholder; col widths computed by caller if needed


def pages_fr(page_w, mx):
    f = "REESKOVA · Présentation Corporative"
    cw = page_w - 2 * mx
    return f, [
        [
            ("h1", "REESKOVA"),
            ("sub", "Présentation corporative pour les entreprises"),
            ("audiences", "Agences immobilières  ·  Concessionnaires  ·  Promoteurs  ·  Partenaires de services  ·  Opérations multi-agences"),
            ("p", "REESKOVA est le marketplace premium de biens immobiliers, véhicules et services porté par RSC Group. Ce document présente, avec un détail opérationnel, l’infrastructure numérique disponible pour les entreprises qui souhaitent publier un inventaire vérifié, capter une demande qualifiée et gérer la relation commerciale avec acheteurs et investisseurs sans confier la conclusion à une agence intermédiaire.", 8.3, 11.2),
            ("p", "La plateforme combine une couche publique de découverte (marketplace B2B2C multilingue et multi-marchés) et une couche privée d’exploitation (Portail Entreprises / Backoffice). RSC / REESKOVA publie et connecte ; la négociation, les formalités et la conclusion restent exclusivement entre l’entreprise annonceur et le client.", 8.3, 11.2),
            ("callout", "Principe institutionnel : REESKOVA est une plateforme de publication et de connexion. Elle n’intermédie pas les contrats, ne conserve pas de fonds et n’assure pas les démarches juridiques. Ce cadre fixe des attentes claires pour les entreprises, les acheteurs et les partenaires de l’écosystème."),
            ("h2", 1, "Objectif de ce document"),
            ("bullets", [
                "Expliquer le positionnement de REESKOVA dans l’écosystème RSC Group et son rôle vis-à-vis de l’entreprise annonceur.",
                "Décrire les verticales, le parcours acheteur, les capacités SaaS et les règles de vérification corporative.",
                "Documenter les flux réels d’intégration, de publication d’inventaire, de contact et de planification de visites.",
                "Définir les limites institutionnelles, les engagements réciproques et les canaux officiels de contact.",
                "Servir de base d’évaluation pour l’intégration d’agences, concessionnaires, promoteurs et partenaires.",
            ]),
            ("h2", 2, "Périmètre opérationnel du produit"),
            ("table", ["Dimension", "Détail"], [
                ["Verticales", "Immobilier, véhicules, services et options de crédit publiées par des partenaires"],
                ["Modèle", "Marketplace B2B2C + Portail Entreprises / Backoffice pour annonceurs vérifiés"],
                ["Marchés", "Configuration multi-marchés avec focus stratégique LATAM+ et international"],
                ["Langues d’interface", "Portugais, espagnol, anglais, français, allemand, italien et arabe"],
                ["Admission des entreprises", "Demande corporative avec vérification avant activation opérationnelle"],
                ["Rôle de RSC", "Publication et connexion ; sans intermédiation de contrats ni conservation de fonds"],
            ]),
            ("h2", 3, "Sommaire"),
            ("toc", [
                "04  RSC Group et définition de REESKOVA",
                "05  Contexte de marché et proposition de valeur",
                "06  Verticales, règles de publication et audiences",
                "07  Parcours acheteur et points de contact",
                "08  Infrastructure SaaS et architecture opérationnelle",
                "09  Intégration, vérification et activation",
                "10  Exploitation quotidienne : publier, leads et visites",
                "11  Découverte, écosystème et gouvernance",
                "12  Canaux officiels et prochaines étapes",
            ]),
            ("label", "Comment utiliser ce document"),
            ("bullets", [
                "Direction générale et partnerships : évaluer l’adéquation stratégique avec l’infrastructure REESKOVA.",
                "Opérations et commercial : revoir le parcours, le panneau SaaS et les flux leads/visites avant l’onboarding.",
                "Juridique / conformité interne : aligner le principe publier-et-connecter avec les politiques de l’entreprise.",
                f"Contact officiel pour avancer : {CONTACT}",
            ]),
        ],
        [
            ("h2", 4, "RSC Group — société mère"),
            ("p", "RSC Group est la société technologique mère d’un écosystème multiproduits orienté infrastructure numérique, marchés et services associés. Son identité institutionnelle — professionnelle, sobre et technology-forward — définit le standard visuel, opérationnel et réputationnel des marques du groupe, dont REESKOVA."),
            ("p", "Le groupe articule des capacités marketplace, chain, wallet, services financiers et technologie appliquée. REESKOVA concentre l’expérience marketplace premium pour l’immobilier, les véhicules et les services, tandis que d’autres unités apportent des couches complémentaires sans modifier le principe de non-intermédiation contractuelle du marketplace."),
            ("h2", 5, "Carte de l’écosystème"),
            ("table", ["Unité / marque", "Rôle"], [
                ["REESKOVA (RSC Market)", "Marketplace B2B2C premium + Portail Entreprises / Backoffice pour annonceurs vérifiés"],
                ["RSC Chain / Reesk Chain", "Infrastructure blockchain et couche technologique chain de l’écosystème"],
                ["RSC Wallet", "Capacités wallet et paiements au sein du groupe"],
                ["RSC Bank · RSC Capital", "Services financiers et capital associés à l’écosystème"],
                ["Ora Technology", "Partenaire technologique du groupe"],
                ["Services auxiliaires", "Couches Escrow, P2P et Corporate lorsqu’elles sont activées dans l’écosystème RSC"],
            ]),
            ("h2", 6, "Définition opérationnelle de REESKOVA"),
            ("p", "REESKOVA est un marketplace B2B2C : les entreprises associées et vérifiées administrent les annonces depuis le Portail Entreprises / Backoffice ; les consommateurs ne publient pas. L’acheteur découvre l’inventaire, contacte l’annonceur, planifie des visites et avance l’achat directement avec l’entreprise. RSC fournit l’infrastructure de publication, découverte, messagerie et agenda ; elle ne remplace pas l’annonceur dans la relation commerciale."),
            ("table", ["Dimension", "Détail institutionnel"], [
                ["Nature juridico-opérationnelle", "Plateforme de publication et de connexion ; pas une agence immobilière ou automobile"],
                ["Modèle B2B", "Infrastructure SaaS et distribution numérique pour entreprises vérifiées"],
                ["Qui publie", "Exclusivement les entreprises associées après onboarding et vérification"],
                ["Qui achète / explore", "Consommateurs, investisseurs et utilisateurs du marketplace public"],
                ["Verticales", "Immobilier, véhicules, services et options de crédit publiées par des partenaires"],
                ["Couverture produit", "Configuration multi-marchés avec communication stratégique LATAM+"],
                ["Langues", "Sept langues d’interface pour une exploitation régionale et internationale"],
                ["Limite explicite", "Sans intermédiation de contrats, sans conservation de fonds, sans démarches juridiques"],
            ]),
            ("callout", "Positionnement résumé : « Un marketplace, pas une agence. » L’entreprise conserve le contrôle commercial ; REESKOVA apporte infrastructure, audience et outils d’exploitation."),
        ],
        [
            ("h2", 7, "Contexte de marché"),
            ("p", "L’environnement numérique de l’immobilier, des véhicules et des services reste fragmenté. Les entreprises opèrent sur des portails verticaux déconnectés, avec une forte concurrence pour les impressions, une faible traçabilité des leads et peu d’intégration entre découverte, contact, visite et suivi commercial. L’acheteur, lui, attend un parcours continu et transparent."),
            ("bullets", [
                "Des portails isolés par verticale obligent à dupliquer inventaire, marque et effort commercial.",
                "La métrique dominante d’impression ne garantit ni conversation ni visite qualifiée.",
                "Sans CRM relié au canal de demande, le lead se perd entre WhatsApp, formulaires et e-mails dispersés.",
                "La confiance de l’acheteur s’érode dans les petites annonces ouvertes peu vérifiées.",
                "LATAM+ et marchés adjacents concentrent une demande numérique croissante en logement, mobilité et services.",
                "Les opérations multi-agences exigent une identité corporative cohérente et un contrôle centralisé de l’inventaire.",
            ]),
            ("h2", 8, "Proposition de valeur REESKOVA pour l’entreprise"),
            ("p", "REESKOVA répond à ce contexte par un écosystème unifié : distribution multi-verticale, leads actionnables dans un panneau, identité vérifiée, et séparation claire entre infrastructure numérique et responsabilité de conclusion."),
            ("two_col", [
                ("Distribution unifiée", "Un seul canal pour immobilier, véhicules et services dans un parcours d’achat cohérent."),
                ("Leads actionnables", "Chats, demandes et visites arrivent dans l’environnement opérationnel de l’entreprise."),
                ("Confiance vérifiée", "Marketplace réservé aux entreprises associées ; sceau RSC visible sur profil et annonces."),
                ("Contrôle commercial", "Prix, négociation, contrat et paiement restent entre annonceur et client."),
                ("Exploitation SaaS", "Annonces, CRM, chat, agenda, analytics et IA sur une infrastructure commune."),
                ("Écosystème élargi", "Financement, assurances et services contextuels sans faire de RSC l’intermédiaire du deal."),
            ], 17 * mm),
            ("h2", 9, "Résultats opérationnels attendus"),
            ("bullets", [
                "Plus grande cohérence de marque en publiant sous identité corporative vérifiée.",
                "Moins de friction entre découverte publique et réponse commerciale interne.",
                "Traçabilité des contacts et visites avec des statuts clairs pour l’équipe commerciale.",
                "Scalabilité multi-marchés et multilingue sans reconstruire le canal.",
                "Alignement juridico-opérationnel : l’entreprise conclut ; la plateforme connecte.",
            ]),
            ("callout", "Focus commercial du produit Pour Entreprises : publier des annonces, recevoir des leads qualifiés et exploiter l’opération dans le panneau SaaS, au sein d’un écosystème conçu pour agences, concessionnaires et promoteurs."),
        ],
        [
            ("h2", 10, "Verticales du marketplace"),
            ("p", "REESKOVA organise l’offre en verticales qui accompagnent la décision d’achat. L’entreprise publie dans la catégorie qu’elle exploite ; l’acheteur navigue l’écosystème avec une expérience continue, filtres, carte et contact direct."),
            ("table", ["Verticale", "Périmètre et dynamique"], [
                ["Immobilier", "Maisons, appartements, terrains, commerces, lancements, copropriétés, plage et campagne ; achat et location. Publication par agences et promoteurs vérifiés, avec fiche enrichie, carte, comparaison et contact."],
                ["Véhicules", "Voitures, SUV, motos et catégories associées, neuf ou occasion. Publication par concessionnaires vérifiés. Le parcours priorise lead rapide, chat et visite au point de vente."],
                ["Services", "Couches du parcours : assurances, déménagement, décoration, énergie, connectivité et partenaires associés. Ils apportent une valeur contextuelle sans faire de REESKOVA l’intermédiaire du service."],
                ["Crédit / financement", "Options publiées par entreprises ou partenaires. Évaluation, approbation et accord financier entre le client et l’entité. Dans le produit, le drapeau crédit est priorisé au Brésil."],
            ], None, 7.1),
            ("h2", 11, "Règles de publication"),
            ("table", ["Règle", "Application"], [
                ["Entreprises vérifiées uniquement", "Les particuliers n’administrent pas d’annonces sur le marketplace"],
                ["Backoffice comme source", "L’inventaire est créé et maintenu dans le panneau entreprise puis synchronisé vers les vitrines publiques"],
                ["Identité corporative", "Nom, logo, document, agences, horaires et canal WhatsApp peuvent être affichés"],
                ["Sceau vérifié", "Signal de confiance sur cartes et fiches lorsque entreprise/annonce sont vérifiées"],
                ["Qualité de contenu", "L’entreprise est responsable de l’exactitude, des mises à jour et de la conformité légale"],
                ["Retrait / suspension", "RSC peut retirer du contenu ou restreindre l’accès en cas de non-conformité ou de risque d’intégrité"],
            ]),
            ("h2", 12, "Audiences entreprises"),
            ("table", ["Audience", "Mode d’exploitation"], [
                ["Agences immobilières", "Publient des biens, reçoivent des contacts qualifiés et connectent visites et options de crédit partenaires."],
                ["Concessionnaires", "Exposent le stock, capturent des leads en temps réel et accélèrent les visites showroom / point de vente."],
                ["Promoteurs", "Lancent des programmes, gèrent les lots et capturent la demande dès les premières phases."],
                ["Agences et retail", "Catégories admises à l’onboarding pour opérations commerciales spécialisées."],
                ["Partenaires de services", "Participent au parcours via assurances, habitat, énergie, financement et offres associées."],
            ]),
        ],
        [
            ("h2", 13, "Parcours acheteur"),
            ("p", "Le parcours est conçu pour convertir la découverte en relation commerciale avec l’entreprise annonceur. Chaque étape génère un événement opérationnel utilisable par l’équipe commerciale. RSC n’organise ni la logistique physique ni la conclusion documentaire."),
            ("steps", [
                ("Cherche", "Explore l’inventaire avec filtres, carte, comparaison et IA"),
                ("Contacte", "Chat RSC, WhatsApp ou demande à l’annonceur"),
                ("Visite", "Planifie date et heure avec l’entreprise"),
                ("Négocie", "Conditions entre client et entreprise"),
                ("Conclut", "Contrats et paiements hors RSC"),
            ], 18 * mm),
            ("h2", 14, "Détail fonctionnel par étape"),
            ("table", ["Étape", "Ce qui se passe / ce que reçoit l’entreprise"], [
                ["Cherche", "L’acheteur parcourt les vitrines immobilier ou véhicules, applique des filtres, change de vues et peut comparer."],
                ["Contacte", "Depuis la fiche, démarre un chat RSC ou WhatsApp. Le fil ou contact est routé vers l’entreprise annonceur."],
                ["Visite", "Complète une demande de rendez-vous ; l’entreprise gère confirmation, annulation ou report depuis son panneau."],
                ["Négocie", "Prix, conditions, documents et due diligence entre les parties, hors intermédiation RSC."],
                ["Conclut", "Signature, paiements, enregistrement et livraison relèvent exclusivement du client et de l’entreprise."],
            ], None, 7.1),
            ("h2", 15, "Points de contact sur la fiche publique"),
            ("p", "La fiche d’annonce concentre les actions qui alimentent l’entonnoir commercial de l’entreprise. Ces actions réduisent la friction et laissent une traçabilité dans l’environnement opérationnel de l’annonceur."),
            ("two_col", [
                ("Chat RSC", "Messagerie dans la plateforme. L’équipe répond depuis le Panneau de leads / Backoffice et conserve l’historique."),
                ("WhatsApp", "Canal rapide lié au numéro corporatif configuré par l’entreprise dans son profil opérationnel."),
                ("Planifier une visite", "Capture du nom, téléphone, e-mail optionnel, date, heure et notes, avec validation de disponibilité."),
                ("Comparer et favoris", "L’acheteur organise des alternatives ; cela augmente l’intention de recontact et la qualité de conversation."),
            ], 18 * mm),
            ("callout", "Principe réaffirmé auprès des acheteurs et des entreprises : RSC ne gère pas les formalités, ne signe pas de contrats, ne conserve pas d’argent et ne conclut pas les opérations. Visite, documentation et livraison restent exclusivement entre client et entreprise."),
            ("h2", 16, "Implications pour l’équipe commerciale"),
            ("bullets", [
                "Un responsable opérationnel doit répondre aux chats et visites avec un SLA interne défini par l’entreprise.",
                "La qualité de l’annonce (médias, données, prix, localisation) conditionne directement la qualité du lead.",
                "La vérification et le sceau RSC renforcent le taux de contact face aux annonces non vérifiées d’autres canaux.",
                "L’usage combiné chat + WhatsApp + agenda couvre différents niveaux d’intention d’achat.",
            ]),
        ],
        [
            ("h2", 17, "Proposition étendue pour l’entreprise"),
            ("p", "Rejoindre REESKOVA ne consiste pas seulement à lister un inventaire. L’entreprise opère dans une infrastructure qui articule distribution publique, identité vérifiée et outils privés de gestion commerciale. La valeur se mesure à la capacité de convertir découverte en conversation et visite."),
            ("h2", 18, "Bénéfices opérationnels"),
            ("bullets", [
                "Un canal de demande aligné sur un inventaire vérifié — pas des petites annonces ouvertes de particuliers.",
                "Centralisation des chats, visites et demandes avec des statuts opérationnels clairs.",
                "Identité corporative visible : marque, document, agences, horaires et WhatsApp sur le marketplace.",
                "Synchronisation des annonces du Backoffice vers des vitrines publiques multilingues et multi-marchés.",
                "Capacité de mettre en avant l’inventaire et d’utiliser des insights IA pour prioriser les actions commerciales.",
                "Séparation nette entre distribution numérique et responsabilité juridique de conclusion.",
                "Scalabilité pour les réseaux qui ont besoin d’une cohérence de marque multi-sites.",
            ]),
            ("h2", 19, "Ce que REESKOVA n’assume pas"),
            ("table", ["Hors périmètre", "Implication pratique"], [
                ["Intermédiation contractuelle", "RSC ne rédige, ne signe ni ne garantit les contrats entre acheteur et entreprise"],
                ["Conservation de fonds", "RSC ne détient pas le prix de l’opération ni n’agit comme escrow du deal marketplace"],
                ["Démarches juridiques / registres", "Les formalités notariales, registres ou réglementaires sont hors plateforme"],
                ["Conclusion et livraison", "L’exécution physique et juridique de l’opération appartient aux parties"],
                ["Approbation de crédit", "S’il existe un financement, l’entité partenaire ou annonceur financier décide"],
            ]),
            ("h2", 20, "Profil d’entreprise idéal"),
            ("p", "REESKOVA s’adresse aux organisations disposant d’un inventaire réel, d’une capacité de réponse commerciale et d’une volonté de maintenir des standards d’exactitude. L’onboarding vérifie l’identité corporative précisément pour préserver cette qualité de réseau."),
            ("bullets", [
                "Dispose d’un inventaire actif de biens, véhicules ou services publié de façon professionnelle.",
                "Dispose d’une équipe ou d’un responsable pour répondre aux leads dans des délais commercialement raisonnables.",
                "Accepte d’opérer sous des règles de marketplace curaté et de vérification.",
                "Souhaite contrôler la relation client jusqu’à la conclusion, sans la céder à une couche d’agence numérique.",
                "Recherche une présence multi-marchés ou multilingue sans fragmenter l’exploitation en outils isolés.",
            ]),
        ],
        [
            ("h2", 21, "Infrastructure SaaS — Portail Entreprises"),
            ("p", "L’exploitation quotidienne se concentre dans le Portail Entreprises / Backoffice. Le marketplace REESKOVA synchronise l’inventaire publié et délivre les événements de demande générés par les acheteurs. Le Backoffice est la source de vérité des annonces et de l’organisation ; le marketplace est la couche de découverte, de contact et d’agenda."),
            ("h2", 22, "Modules de l’environnement entreprise"),
            ("table", ["Module", "Fonction"], [
                ["Gestion des annonces", "Création, édition, mises en avant, médias et contrôle d’inventaire actif"],
                ["CRM de leads", "Organisation des contacts, demandes et visites dans un flux unique"],
                ["Chat intégré", "Réponse aux fils RSC avec continuité et historique"],
                ["Agenda des visites", "Gestion des demandes avec statuts pending, confirmed, cancelled et reschedule_proposed"],
                ["Analytics", "Visibilité de performance par annonce, région et conversion"],
                ["Sceau vérifié", "Signal public de confiance associé au profil et aux fiches"],
                ["IA commerciale", "Insights et priorisation pour mettre en avant l’inventaire"],
                ["WhatsApp corporatif", "Canal rapide lié au profil de l’organisation"],
                ["Données d’organisation", "Logo, identifiant fiscal, agences, horaires et contacts"],
                ["Extensions réseau", "Multi-agences et intégrations API pour opérations à plus grande échelle"],
            ], None, 7.1),
            ("h2", 23, "Architecture opérationnelle"),
            ("table", ["Couche", "Comportement"], [
                ["Backoffice entreprises", "Administration de l’inventaire et de l’organisation ; source de vérité des listings"],
                ["API marketplace", "Synchronisation des annonces vers les vitrines publiques"],
                ["Événements de demande", "Chats, visites et contacts générés publiquement et consommés par l’entreprise"],
                ["Profil vérifié", "Attributs de confiance visibles sur cartes, détail et recherche"],
                ["Buyer hub", "L’acheteur conserve aussi favoris, comparaisons et visites dans son espace"],
            ]),
            ("h2", 24, "Implications de gouvernance des données"),
            ("bullets", [
                "L’entreprise est responsable du contenu publié et des données reçues hors plateforme.",
                "REESKOVA traite les données de compte, publication, découverte, messagerie et visites selon ses politiques.",
                "Les partenaires financiers ou de services intervenant après contact restent indépendamment responsables de leurs processus.",
                "La vérification d’onboarding peut exiger une identification corporative et une validation des contacts.",
            ]),
            ("callout", "Conception délibérée : séparer distribution (marketplace) et exploitation (SaaS) permet de faire croître l’audience sans obliger l’entreprise à céder le contrôle de la conclusion commerciale."),
        ],
        [
            ("h2", 25, "Processus d’intégration"),
            ("p", "L’admission des entreprises est vérifiée. Le processus protège la qualité du marketplace et la confiance de l’acheteur. Ce n’est pas une inscription immédiate sans contrôle : l’activation opérationnelle intervient après validation de l’équipe RSC."),
            ("steps", [
                ("Demande", "Formulaire corporatif dans Pour Entreprises"),
                ("Revue", "Validation d’identité et des données sous 24 h"),
                ("Activation", "Identifiants et accès Backoffice"),
                ("Mise en route", "Profil, inventaire et traitement des leads"),
            ], 18 * mm),
            ("h2", 26, "Informations requises dans la demande"),
            ("table", ["Champ", "Finalité"], [
                ["Nom de l’entreprise", "Identification commerciale / raison sociale pour le profil corporatif"],
                ["Identifiant fiscal / document", "Validation de l’existence et de l’identité corporative"],
                ["E-mail corporatif", "Canal pour la communication d’onboarding et la livraison d’accès"],
                ["Téléphone / WhatsApp", "Contact opérationnel pendant la vérification et l’activation"],
                ["Catégorie", "Classification : real estate, automotive, agency, retail ou services"],
            ]),
            ("h2", 27, "Traitement de la demande"),
            ("bullets", [
                "La demande est enregistrée avec un statut initial pending pour revue interne.",
                "L’équipe RSC peut demander des informations complémentaires de vérification corporative.",
                "Les demandes en double en statut pending sont rejetées pour éviter les doubles inscriptions.",
                "Après approbation, les instructions d’accès au Portail Entreprises / Backoffice sont envoyées.",
                "L’entreprise configure profil, identité visuelle, agences et canaux de contact avant ou lors de la publication.",
            ]),
            ("h2", 28, "Activités après approbation"),
            ("table", ["Activité", "Résultat attendu"], [
                ["Accès Backoffice", "L’équipe autorisée entre dans l’environnement d’administration"],
                ["Configuration organisation", "Logo, document, agences, horaires et WhatsApp opérationnel"],
                ["Publication initiale", "Premier ensemble d’annonces actives dans la verticale concernée"],
                ["Vérification visible", "Activation du sceau selon la validation de l’équipe RSC"],
                ["Exploitation de la demande", "Traitement des chats et visites depuis le panneau de leads"],
                ["Optimisation", "Usage des mises en avant, analytics et insights pour prioriser l’inventaire"],
            ]),
            ("callout", f"Canal de demande : section Pour Entreprises dans REESKOVA. Contact institutionnel : {CONTACT}"),
        ],
        [
            ("h2", 29, "Opération A — publier l’inventaire"),
            ("p", "La publication est administrée dans le Backoffice. Une fois active, l’annonce se synchronise avec le marketplace et devient disponible dans les vitrines publiques. La qualité des données et des médias détermine la capacité de conversion."),
            ("steps", [
                ("Créer", "Données, prix, localisation, attributs"),
                ("Médias", "Photos, vidéo et matériaux visuels"),
                ("Publier", "Statut actif dans le Backoffice"),
                ("Synchroniser", "Exposition en vitrine publique"),
                ("Optimiser", "Mises en avant, analytics et insights"),
            ], 17 * mm),
            ("bullets", [
                "L’annonce doit maintenir prix, disponibilité et attributs à jour pour éviter les leads invalides.",
                "Des médias professionnels et une géolocalisation correcte améliorent la découverte via carte et filtres.",
                "Les mises en avant et insights IA aident à prioriser les lots ou véhicules à demande relative plus élevée.",
                "L’entreprise conserve la faculté de suspendre ou retirer l’inventaire depuis son environnement d’administration.",
            ]),
            ("h2", 30, "Opération B — du contact au lead"),
            ("table", ["Étape", "Description"], [
                ["1", "L’acheteur ouvre la fiche publique de l’annonce dans la vitrine concernée."],
                ["2", "Sélectionne chat RSC ou WhatsApp comme premier canal de contact."],
                ["3", "Un fil ou contact est généré vers l’entreprise annonceur."],
                ["4", "L’équipe répond depuis le Panneau de leads / Backoffice selon son protocole interne."],
                ["5", "La conversation reste disponible pour suivi, qualification et conclusion commerciale externe."],
            ], [cw * 0.10, cw * 0.90]),
            ("h2", 31, "Opération C — planification de visite"),
            ("table", ["Étape", "Description"], [
                ["1", "L’acheteur choisit l’action de planifier une visite sur la fiche."],
                ["2", "Saisit les coordonnées, la date, l’heure et les notes pertinentes."],
                ["3", "Le système valide la demande selon la disponibilité définie par l’entreprise."],
                ["4", "La visite est enregistrée dans un statut initial en attente de gestion."],
                ["5", "L’entreprise confirme, annule ou propose un report ; l’acheteur voit le statut dans son espace."],
            ], [cw * 0.10, cw * 0.90]),
            ("callout", "Statuts de visite utilisés en exploitation : pending, confirmed, cancelled et reschedule_proposed. Cette machine d’états permet le suivi commercial sans que RSC n’intervienne dans la logistique physique."),
            ("h2", 32, "Bonnes pratiques opérationnelles"),
            ("bullets", [
                "Définir des délais maximaux de première réponse pour chat et visites.",
                "Maintenir des créneaux d’agenda réalistes pour éviter les annulations systématiques.",
                "Unifier les critères de qualification des leads entre agences lorsqu’il existe un réseau.",
                "Enregistrer dans le CRM interne de l’entreprise le résultat après contact (le cas échéant).",
            ]),
        ],
        [
            ("h2", 33, "Capacités de découverte"),
            ("p", "Au-delà du panneau B2B, REESKOVA propose des outils publics qui élèvent la qualité du trafic vers l’inventaire de l’entreprise. Ces capacités existent pour améliorer l’intention, pas seulement le volume de visites."),
            ("two_col", [
                ("Cartes et géographie", "Vues liste, galerie, carte et satellite ; navigation hiérarchique et géocodage pour la découverte locale."),
                ("Comparateur", "Comparaison de biens et véhicules, favoris et continuité entre session invité et compte."),
                ("Reeskova AI", "Recherche en langage naturel et insights orientés priorisation commerciale de l’inventaire."),
                ("Financement visible", "Signalisation d’options de crédit partenaires ; l’accord reste avec l’entité."),
                ("Multilingue", "Interface en sept langues pour marchés régionaux et internationaux."),
                ("Sceau vérifié", "Badge public sur cartes et fiches pour renforcer la confiance de l’acheteur."),
            ], 18 * mm),
            ("h2", 34, "Surfaces produit pertinentes"),
            ("table", ["Surface", "Fonction"], [
                ["Pour Entreprises", "Entrée corporative B2B et explication de valeur pour les annonceurs"],
                ["Inscription entreprise", "Formulaire de demande d’intégration et de vérification"],
                ["Vitrine immobilière", "Découverte publique des biens"],
                ["Vitrine véhicules", "Découverte publique de l’inventaire automobile"],
                ["Services / financement", "Couches du parcours et options de crédit partenaires"],
                ["Portail Entreprises / Backoffice", "Administration de l’inventaire, de l’organisation et de la demande"],
            ]),
            ("h2", 35, "Signaux de confiance au marché"),
            ("bullets", [
                "Marketplace réservé aux entreprises associées — pas un tableau d’annonces ouvert aux particuliers.",
                "Vérification d’onboarding avant l’accès opérationnel complet.",
                "Identité corporative visible sur les fiches et résultats de recherche.",
                "Transparence institutionnelle sur le rôle de RSC : publie et connecte ; les limites sont explicites.",
                "Politiques d’usage, de confidentialité et de conformité disponibles dans le produit.",
            ]),
            ("h2", 36, "Implication pour la stratégie commerciale"),
            ("p", "L’entreprise qui opère dans REESKOVA doit traiter le canal comme une infrastructure de demande et de réputation. La cohérence de l’inventaire, la vitesse de réponse et la clarté de l’identité corporative sont les facteurs qui transforment la présence en résultats commerciaux mesurables."),
        ],
        [
            ("h2", 37, "Écosystème autour de la décision"),
            ("p", "REESKOVA s’inscrit dans un parcours élargi au sein de l’écosystème RSC Group. Partenaires et unités du groupe peuvent apporter des couches complémentaires — financement, assurances, habitat, énergie — sans modifier le principe selon lequel la conclusion de l’opération principale reste entre client et entreprise annonceur."),
            ("table", ["Couche", "Contribution"], [
                ["Financement", "Options de crédit visibles au moment de la décision ; accord avec l’entité correspondante"],
                ["Assurances", "Protection contextuelle associée au bien ou au véhicule"],
                ["Habitat et énergie", "Services post-décision : déménagement, aménagement, solaire, connectivité"],
                ["Groupe RSC", "RSC Group, RSC Chain, wallet, bank, capital et partenaires technologiques"],
            ]),
            ("h2", 38, "Cadre institutionnel et juridique"),
            ("p", "Le positionnement juridique de REESKOVA est délibérément borné. Cette clarté réduit l’ambiguïté réglementaire et aligne les attentes entre RSC, entreprises et utilisateurs finaux."),
            ("bullets", [
                "REESKOVA / RSC Market opère comme plateforme de publication et de connexion dans l’écosystème RSC Group.",
                "Elle n’intermédie pas contrats, paiements ni démarches juridiques entre acheteur et annonceur.",
                "Elle n’agit pas comme agence immobilière intermédiaire, concessionnaire, escrow ou cabinet juridique.",
                "Les annonceurs et institutions partenaires sont indépendamment responsables de leurs processus et obligations.",
                "Les entreprises doivent maintenir des informations exactes, des annonces conformes et une attention responsable à la demande reçue.",
                "RSC peut appliquer des contrôles qualité, vérification et suspension pour protéger l’intégrité du marketplace.",
            ]),
            ("h2", 39, "Engagements réciproques"),
            ("table", ["RSC Group", "Entreprise participante"], [
                ["Fournir l’accès à l’infrastructure REESKOVA", "Fournir des données corporatives exactes et à jour"],
                ["Coordonner l’activation via l’équipe partnerships", "Maintenir des annonces responsables et actuelles"],
                ["Préserver un marketplace curaté et vérifié", "Traiter leads et visites selon un standard professionnel"],
                ["Respecter l’image de marque du partenaire", "Respecter l’identité institutionnelle RSC / REESKOVA"],
                ["Maintenir des canaux officiels de contact", "Désigner un contact opérationnel interne permanent"],
            ], [cw * 0.5, cw * 0.5], 7.0),
            ("callout", "Toute collaboration commerciale spécifique, annexe créative ou condition particulière entre RSC et une entreprise doit être documentée par écrit. Ce document est une présentation corporative informative, pas un contrat."),
        ],
        [
            ("h2", 40, "Comment intégrer votre entreprise"),
            ("p", "Pour opérer sur l’infrastructure REESKOVA, l’entreprise complète l’inscription corporative dans la section Pour Entreprises ou écrit à l’équipe RSC. L’onboarding inclut vérification, activation d’accès et accompagnement pour le lancement du profil et de l’inventaire initial."),
            ("steps", [
                ("Entrer", "REESKOVA → Pour Entreprises"),
                ("S’inscrire", "Demande corporative complète"),
                ("Vérifier", "Revue RSC sous 24 h"),
                ("Activer", "Accès Backoffice et inventaire"),
            ], 18 * mm),
            ("h2", 41, "Canaux officiels"),
            ("table", ["Canal", "Détail"], [
                ["Inscription web", "REESKOVA → Pour Entreprises → inscription entreprise"],
                ["E-mail corporatif", EMAIL],
                ["Téléphone (France)", PHONE],
                ["Site corporatif", WEB],
                ["Objet recommandé", "Intégration entreprise — REESKOVA"],
                ["Informations à inclure", "Nom légal, pays/marché, verticale, volume approximatif d’inventaire et contact opérationnel"],
            ]),
            ("h2", 42, "Checklist de préparation"),
            ("bullets", [
                "Disposer d’un identifiant fiscal / document corporatif valide.",
                "Définir e-mail et téléphone opérationnels pour vérification et support.",
                "Préparer l’identité visuelle (logo) et les données d’agences/horaires le cas échéant.",
                "Sélectionner l’inventaire initial à publier après activation.",
                "Nommer un responsable interne d’onboarding et de réponse aux leads.",
                "Revoir en interne le principe de non-intermédiation pour aligner les attentes de l’équipe commerciale.",
            ]),
            ("h2", 43, "FAQ d’intégration"),
            ("table", ["Question", "Réponse institutionnelle"], [
                ["Qui peut publier ?", "Uniquement les entreprises associées et vérifiées. Les particuliers n’administrent pas d’annonces."],
                ["RSC intermédie-t-elle la conclusion ?", "Non. Elle publie et connecte ; négociation, contrat et paiement sont entre les parties."],
                ["Combien de temps dure la vérification ?", "Le processus standard de revue est de jusqu’à 24 heures ouvrées d’analyse."],
                ["Quelles verticales sont admises ?", "Immobilier, véhicules, services et catégories associées d’onboarding."],
                ["Où administrer l’inventaire ?", "Dans le Portail Entreprises / Backoffice, synchronisé avec le marketplace public."],
            ], None, 6.9),
            ("h2", 44, "Clôture"),
            ("p", "REESKOVA offre aux entreprises une infrastructure numérique pour publier, capter la demande et exploiter la relation commerciale avec une clarté des rôles. Le marketplace distribue et connecte ; l’entreprise décide, négocie et conclut. L’intégration s’adresse aux organisations qui valorisent vérification, contrôle commercial et exploitation professionnelle du canal numérique."),
            ("callout", f"One Marketplace. Endless Opportunities. — REESKOVA by RSC Group  ·  {CONTACT}"),
            ("p", f"Avis : REESKOVA / RSC Market est une plateforme de publication et de connexion opérée dans l’écosystème RSC Group. Elle n’intermédie pas les contrats, ne conserve pas de fonds et n’assure pas les démarches juridiques. Ce document est informatif et institutionnel ; il ne constitue ni offre contraignante ni conditions commerciales définitives. Pour des conditions particulières, écrivez à {EMAIL} ou appelez le {PHONE}. Site corporatif : {WEB}.", 7.0, 9.5),
            ("brand",),
        ],
    ]
